# Generated by Django 3.0.2 on 2020-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
