# Generated by Django 3.0.2 on 2020-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200129_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='function',
            name='step',
            field=models.IntegerField(),
        ),
    ]
