# Generated by Django 3.0.2 on 2020-01-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200129_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
