# Generated by Django 3.0.2 on 2020-02-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200131_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='exception_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='function_text',
            field=models.CharField(max_length=100),
        ),
    ]
